version: "3.5"

services:
  app:
    container_name: app
    image: app:latest
    volumes:
      - ./trim:/src/app/trim
      - ./thumnail:/src/app/thumnail
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 50M
